import { Box, Skeleton, Table } from "@chakra-ui/react";

export const SkeletonLoader = () => {
  return (
    <Box
      bg="surface"
      border="1px solid"
      borderColor="card.border"
      borderRadius="xl"
      overflow="hidden"
      boxShadow="sm"
    >
      <Table.Root>
        <Table.Header>
          <Table.Row>
            <Table.ColumnHeader>Identity</Table.ColumnHeader>
            <Table.ColumnHeader>Status</Table.ColumnHeader>
            <Table.ColumnHeader>Uptime</Table.ColumnHeader>
            <Table.ColumnHeader>Performance</Table.ColumnHeader>
            <Table.ColumnHeader>Last Heartbeat</Table.ColumnHeader>
            <Table.ColumnHeader>Storage</Table.ColumnHeader>
            <Table.ColumnHeader>Reputation</Table.ColumnHeader>
            <Table.ColumnHeader>Action</Table.ColumnHeader>
          </Table.Row>
        </Table.Header>
        <Table.Body className="loader">
          {Array.from({ length: 5 }).map((_, idx) => (
            <Table.Row key={idx}>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
              <Table.Cell>
                <Skeleton
                  height="24px"
                  width="100%"
                  bg="gray.100"
                  opacity={0.2}
                />
              </Table.Cell>
            </Table.Row>
          ))}
        </Table.Body>
      </Table.Root>
    </Box>
  );
};
